### ISSUE TITLE
Improve metrics provided by the plugin

### ISSUE THREAD

**Issue by scholzj** [strimzi/kafka-quotas-plugin#15]
Currently, the plugin provides two metrics:
* The soft limit value
* The total used storage bytes

It seems that some more metrics would have been useful as well. For example:
* Hard limit
* A flag whether the storage quota is triggered or not
* The current produce limit (which can change between soft and hard limit)

Unless there was some reason why to not add these (performance etc.), we should probably add them.

**Comment by k-wall** [comment]
> A flag whether the storage quota is triggered or not

Maybe an additional metric might help some users, but for our use-case, we've found observing:

* kafka.server<type=Produce, quota.type=PRODUCE|FETCH><>throttle-time
* kafka.server<type=Produce, quota.type=PRODUCE|FETCH><>byte-rate

 coupled with the soft limit/total used storage bytes metrics, is proving sufficient to understand the behaviour of this plugin. 

+1 to the other ideas.

**Comment by k-wall** [comment]
* The current produce limit (which can change between soft and hard limit)

@scholzj - can you expand on this idea?  I'm trying to understand what it is behaviour would be and how it would be useful.   With the hard, soft, and byte-rate values it would be easy in Grafana (or other visualisation tool) to understand your application's usage w.r.t the two limits.   What would this new metric bring?

**Comment by scholzj** [comment]
> @scholzj - can you expand on this idea? I'm trying to understand what it is behaviour would be and how it would be useful. With the hard, soft, and byte-rate values it would be easy in Grafana (or other visualisation tool) to understand your application's usage w.r.t the two limits. What would this new metric bring?

Seems like useful information to know what the actual setting is. It can be probably calculated elsewhere as well, but it can equally be provided by the Quota plugin which already calculates it.

**Comment by k-wall** [comment]
>> The current produce limit (which can change between soft and hard limit)

> Seems like useful information to know what the actual setting is. It can be probably calculated elsewhere as well, but it can equally be provided by the Quota plugin which already calculates it.

I am not understanding the idea.  What is the actual value that the metric would report?

**Comment by scholzj** [comment]
You have the soft limit and the hard limit. After the soft limit is reached, the produce quota is gradually reduced to 0 when the hard limit is reached. So while the storage utilization is somewhere in between soft and hard limit, the produce quota will be also somewhere between the otiginal produce quota and 0. And the actual number which is currently used should be reported.

E.g., when you have:

```
client.quota.callback.static.produce=1000000 # 1MB/s
client.quota.callback.static.storage.soft=80000000000 # 80GB
client.quota.callback.static.storage.hard=100000000000 # 100GB
```

and the actual storage utilization is 90GB, the actual produce quota will not be 0 or 1MB/s but for example 0.5 MB/s.

**Comment by scholzj** [comment]
Ok, if we already have these metrics then it should be fine.
