### ISSUE TITLE
Improve support for JBOD storage

### ISSUE THREAD

**Issue by scholzj** [strimzi/kafka-quotas-plugin#2]
The storage quota doesn't have currently a very good support for JBOD storage. It sums up the used space across all log directories and evaluates it against the quota. But that does not take into account that one disk might be getting full while other is empty because they have different partitions assigned. Therefore you can still run out of disk space without actually breaching the quota.

**Comment by SamBarker** [comment]
Yes I think so. The plugin doesn't have any explicit knowledge of jbod but it does deal with the issues outlined in the description
