### ISSUE TITLE
Investigate possibility of per-listener configuration

### ISSUE THREAD

**Issue by scholzj** [strimzi/kafka-quotas-plugin#3]
It might be handy to be able to configure the produce / fetch quotas per listener. For example users might be interested in having different quotas for internal and external listeners. It would also allow us to isolate internal clients (such as TO) from being impacted by the quotas.

**Comment by alesj** [comment]
Where would the listener info come from?
Info the `quotaLimit` method ...

**Comment by scholzj** [comment]
This is currently no planned.
